version: '3.4.4'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=valentin04
      - POSTGRES_DB=marketplace_db
    ports:
      - "5432:5432"

